### PR TITLE
Fixes ConcatJSON() when concatenating with nulls

### LINKED ISSUE #15: ConcatJSON produce garbled JSON on null
When marshalling JSON with go-swagger generated marshaller for AllOf structures, I stepped on a problem when structures are not initialized.

When the model marshaller concats the following JSON the result is garbled because of a trailing "null" object.

Marshalled value Part 1:
`{ ...,"timeSettled": "0001-01-01T00:00:00.000Z", "timeSubmitted":null}`

Marshalled value Part 2:
`null`

Result from concatJSON:
`{ ...,"timeSettled": "0001-01-01T00:00:00.000Z", "timeSubmitted":null,ull`

This issue probably occurs because of the upgrade on mailru/easyjson, which gets some new fixes with null values.

I suggest to simply fix the concat by not doing anything when the passed blob is equal to null.
What do you think?

### PR DESCRIPTION
**Pull request by fredbi**
fixes #15

### CODE REVIEW

**Comment by fredbi** [comment]
- fixes #15

File: json.go [hunk 1]
```diff
@@ -90,16 +90,29 @@ func ConcatJSON(blobs ...[]byte) []byte {
 	if len(blobs) == 0 {
 		return nil
 	}
-	if len(blobs) == 1 {
+
+	last := len(blobs) - 1
+	for bytes.Equal(blobs[last], []byte("null")) || blobs[last] == nil {
```
Comment (casualjim) [inline json.go]: can you move []byte("null") to a constant / package level var, or replace it with: 

```go
lb := blobs[last]
for len(lb) == 0 || (len(lb) >= 4 && lb[0] == 'n' && lb[1] == 'u' && lb[2] == 'l' && lb[3] == 'l')
```

consider moving the nil check as first check so that it fails faster before trying to read.

Comment (fredbi) [reply json.go]: OK for moving the nil before. Good.
OK for a global var: this would avoid allocation

Regarding the scan optimization proposal, I am not sure this would be much better than the optimized inline assembly-language used by bytes to implement bytes.Equal()
